version: '3'
#https://www.digitalocean.com/community/tutorials/how-to-set-up-laravel-nginx-and-mysql-with-docker-compose-ru
services:

  #PHP Service
  app:
    build:
      context: dockerfile/app
      dockerfile: Dockerfile
#    image: digitalocean.com/php
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    volumes:
      - ./:/project
      - .ssh:/root/.ssh
    networks:
      project_net:
  run-first:
    build:
      context: dockerfile/app
      dockerfile: Dockerfile
    #    image: digitalocean.com/php
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    volumes:
      - ./:/project
      - .ssh:/root/.ssh
    command: "bin/console  service-job:run-first"
    networks:
      project_net:
  #Nginx Service
  webserver:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
#      - "443:443"
    volumes:
      - ./:/project
      - ./dockerfile/webserver/conf.d/:/etc/nginx/conf.d/
    networks:
      project_net:
        ipv4_address: 11.132.10.80
networks:
  project_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 11.132.10.0/24
